books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index.as_view(), name="index"),
    
    path('register/', views.userFormView.as_view(), name='userform'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('home/', views.home.as_view(), name='main'),
    path("<pk>/", views.detail.as_view(), name="details"),
    # path("blog/<int:pk>/", views.detail.as_view(), name="details"),

]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

books/models.py
from django.db import models

# Create your models here.

class Collection(models.Model):
    collection_name = models.CharField(max_length=100)
    # description = models.CharField(max_length=200)
    coll_cover = models.CharField(max_length=1000)
    # coll_buy = models.CharField(max_length=5000)

    def __str__(self):
        return self.collection_name ## This will help return the actual name as wanted


class Piece(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE) #This will link this table to the collection table
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=50)
    author = models.CharField(max_length=200)
    year = models.IntegerField()
    piececover = models.CharField(max_length=1000)
    coll_buy = models.CharField(max_length=5000,  default='default value')

    def __str__(self):
        return self.title
    
class Home(models.Model):
    home_page = models.CharField(max_length=2000)
    # description = models.CharField(max_length=200, default='home')
    home_cover = models.CharField(max_length=1000, default="page")

    def __str__(self):
        return self.home_page

books/forms.py
# To create a blueprint for the registration form
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm): #This is the form class

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:  # This simply means the definition of class
        model = User
        fields = ['username', 'email', 'password'] #These are the fiels that are required of a user
        
class LoginUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'password']

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Collection, Piece, Home
from django.views import generic
from django.contrib import messages
from .forms import UserForm, LoginUserForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, CreateView # This will work for the View in the form class 

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
# def index(request):
#     all_collection = Collection.objects.all() 
#     context = {
#         "all_collections" : all_collection
#     }
#     return render(request, "books//bookstemplate.html", context)

## To write a neater code using the generic function

# class index(generic.ListView):
#     template_name='books/home.html'

#     def get_queryset(self):
        
#         return Home.objects.all()


class index(generic.ListView):
    template_name='books/books.html'

    def get_queryset(self):
        
        return Collection.objects.all()




# def details(request, books_id):
#     citem = Collection.objects.get(pk=books_id)
#     pitems = Piece.objects.filter(collection=citem)
#     context = {
#         "pitems" : pitems
#     }
#     return render(request, "books\\detailstemplate.html", context)


## To write a neater code using the generic function


# class blog (generic.ListView): # DetailView always accept one parameter
#     template_name='books/books.html'

#     def get_queryset(self):
        
#         return Collection.objects.all()




class home (generic.ListView): # DetailView always accept one parameter
    template_name='books/home.html'

    def get_queryset(self):
        
        return Home.objects.all()



class detail (generic.DetailView): # DetailView always accept one parameter
    model = Collection
    template_name='books/detailstemplate.html'
   


class userFormView(generic.CreateView):
    form_class=UserForm
    template_name = 'books/register.html'
    success_url = reverse_lazy('login') 

    def get(self,request):
        # form = self.form_class
        form = self.form_class(None)
        return render (request, self.template_name,{'form':form})
    
    
    
    def post(self,request):
        form = self.form_class(request.POST)

        ## To register and authenticate a user
        if form.is_valid():
            user=form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()

            newuser=authenticate(username=username, password=password)

            if newuser is not None:
                if newuser.is_active:
                    login(request,newuser)
                    return redirect("/books")
                
        ## If the user is not authenticated, that is he does not exist, or fill in wrong details, give them another form to fill
        return render (request, self.template_name,{'form':form})
    

class Login (LoginView):
    template_name = 'books/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("main") #the reverse_lazy function works with the url name 

def logout_view(request):
    logout(request)
    messages.success(request, "You have successfully logged out")
    return redirect('/books/home')
       


    
            
            
            

books/templates/books/base.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</head>
<body>
    <<nav class="navbar navbar-expand-lg navbar-light bg-light", class="navbar navbar-inverse"> 
    <nav  class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/books">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!<ul class="navbar-nav me-auto mb-2 mb-lg-0", class="nav navbar-nav navbar-right"> -
                    <ul  class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <a  href="/books/register">SignUp</a>
                    </li>
                    <li class="nav-item">
                        To display the registered user 
                        <a {{request.user}}></a> 
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                    </ul>
                    <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
                
        </div>
      </nav>



</body>
</html> -->


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg mr-auto navbar-dark bg-dark navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <span class="navbar-brand mb-0 h1"><a  style="color: red;" ><h2><i>Unique Library</i></h2></a></span>

          <span class="navbar-brand mb-0 h1"><a class="navbar-link" style="color: white;" href="/books/home" >Home</a></span>
        </div>


        <ul class="nav navbar-nav navbar-right">
          {% if not user.is_authenticated %}
          
            <li class="">
              <a class="navbar-link" style="color:  rgb(174, 174, 177);" href="/books/register">Signup</a>
            </li>
            <li class="ml-3">
              <a class="navbar-link" style="color: rgb(174, 174, 177);" href="/books/login">Login</a>
            </li>

            <li class="ml-3">
              <a class="navbar-link" style="color: white;" href="">About Us</a>
            </li>

            <li class="ml-3">
              <a class="navbar-link" style="color: white;" href="">FAQ</a>
            </li>
          
          {% else %}

          <div> <span class="navbar-brand mb-0 h1"><a class="navbar-link" style="color: white;" href="/books" >Blog</a></span></div>

            <li class="ml-3">
              <a class="navbar-link" style="color:red;" href="/books/logout">Logout</a>
            </li>
         
            <li class="ml-3">
              <a class="navbar-link" style="color: white;" href="">About Us</a>
            </li>

            <li class="ml-3">
              <a class="navbar-link" style="color: white;" href="">FAQ</a>
            </li>

            </li>
            <li class="ml-3">
                <a class="navbar-link" style="color: white;">Welcome {{ request.user }}</a>
            </li>

            

          {% endif %}
        </ul>
      </div>
    </nav>

    <br />
   
 
     <div class="container" style="margin-bottom: 20px;"> <!--Add margin-bottom to create spacing at the bottom -->
      {% block content %}

      {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

books/templates/books/books.html
<!DOCTYPE html>
{% extends 'books/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* .book-item {
            text-align: center;
            text-align: center;
            display: flex;
        }
        .book-item h2 {
            font-size: 1.4rem;
            
        }
        .book-item h3 {
            font-size: 1.2rem;
        }
        
    </style> */
</head>

<body>
    {% block content %}
        <div class="container">
            <div class="row">
                {% for booksobj in object_list %}
                <div class="col-md-3 mb-3">
                    <div class="book-item">
                        <img src="{{booksobj.coll_cover}}" class="img-fluid" alt="Book Cover" style="height: 200px; width:200px; ">
                        <h5><a href="/books/{{booksobj.id}}/">{{booksobj.collection_name}}</a></h5>
                        <h5 >{{booksobj.description}}</h5>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endblock %}
</body>
</html>

books/templates/books/detailstemplate.html
<!DOCTYPE html>
{% extends 'books/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .book-item {
            text-align: center;
            text-align: center;
        }
        /* .book-item text-muted {
            font-size: 1rem;
        }
        .book-item h3 {
            font-size: 1rem;
        }*/
        /* .h4 {
            font-size: 0.3rem;
        } */
         
    </style>
</head>
<body>
{% block content %}
    <div class="container">
        <div class="row">
            {% for pieceobj in collection.piece_set.all %}
            <div class="col-md-3 mb-4">
                <div class="book-item">
                    <img src="{{pieceobj.piececover}}" class="img-fluid" alt="Book Cover" style="max-height: 200px;">
                    <h4 class="h4">{{pieceobj.title}}</h4>
                    <h3 class="h6">{{pieceobj.author}} </h3>
                    <h6 class="text-muted">{{pieceobj.year}}</h6>
                    <h2><a href="{{ pieceobj.coll_buy }}" style="font-size: 1.0rem;">Add to cart</a></h2>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</body>
</html>

books/templates/books/home.html
<!DOCTYPE html>
{% extends 'books/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .homeobj-item {
            text-align: center;
        }
        
        .homeobj-item img {
            height: 100%;
            width: 100%;
            object-fit: cover;
        }
    </style>
</head>
<body>
{% block content %}
    <div class="container-fluid">
        <div class="row">
            {% for homeobj in object_list %}
            <div class="col-md-3 mb-4">
                <div class="homeobj-item">
                    <img src="{{homeobj.home_cover}}" class="img-fluid" alt=" Home">
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</body>
</html>

</html>

books/templates/books/login.html
{% extends 'books/base.html' %}
{% block content %}
    

    <div class="card-body">
        <form method="POST">
            {%csrf_token%}
            {{form.as_p}}
            <input class="button" type="submit" value="Login">
        
        </form>
        
</div>



{% endblock content %}

books/templates/books/register.html
<!DOCTYPE html>
{% extends 'books/base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
</head>
<body>
    {% block content %}
        <form action="" method="post">
            <!-- always include in cross site requset forgery(csrf) token whenever youre using a post method and not using external url-->
            {%csrf_token%}
            <div>
                username:
                <input type="text" name="username">
                <br />
                email:
                <input type="email" name="email">
                <br />
                password:
                <input type="password" name="password">
                <br />
                <input type="submit" value="submit">
    
            </div>
           
        </form>
    {% endblock %}
</body>
</html>